#!/usr/bin/env bash
# evaluate-matrix.sh — Interactive evaluation of voice matrix WAV files
#
# Play each file, collect ratings (1-5) and notes, output structured evaluation.
# Order: speaker → tone → temperature (3 temps liền nhau cho dễ A/B compare)
#
# Usage: ./scripts/evaluate-matrix.sh
# Controls: Enter=next, r=replay, s=skip, q=quit (saves progress)
# Resume: re-run to continue where you left off

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
MATRIX_DIR="$PROJECT_DIR/assets/test-sach/voice-matrix"
EVAL_FILE="$MATRIX_DIR/evaluation.md"

# --- Configuration (must match test-voice-matrix.sh) ---
SPEAKERS=("bookie-hai" "fonos")
TEMPERATURES=("0.3" "0.65" "0.85")
TEMP_LABELS=("t03" "t065" "t085")
TONES=("calm" "excited" "reflective" "heavy" "motivational")
TOTAL=$((${#SPEAKERS[@]} * ${#TONES[@]} * ${#TEMPERATURES[@]}))

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

# --- Check ffplay ---
if ! command -v ffplay &>/dev/null; then
  echo -e "${RED}Error: ffplay not found. Install ffmpeg.${NC}"
  exit 1
fi

# --- Check matrix directory ---
if [[ ! -d "$MATRIX_DIR" ]]; then
  echo -e "${RED}Error: Matrix directory not found: $MATRIX_DIR${NC}"
  echo "Run test-voice-matrix.sh first."
  exit 1
fi

# --- Parse existing evaluation for resume ---
declare -A RATED_FILES  # key="speaker/tone-tlabel" value="1"

parse_existing_eval() {
  if [[ ! -f "$EVAL_FILE" ]]; then
    return
  fi
  local in_table=0
  while IFS= read -r line; do
    # Detect table rows (start after header separator)
    if [[ "$line" =~ ^\|\ *---\| ]]; then
      in_table=1
      continue
    fi
    if [[ $in_table -eq 1 ]] && [[ "$line" =~ ^\| ]]; then
      # Parse: | # | Speaker | Tone | Temp | Rating | Duration | Notes |
      local speaker tone temp_label rating
      speaker=$(echo "$line" | awk -F'|' '{gsub(/^[ `]+|[ `]+$/, "", $3); print $3}')
      tone=$(echo "$line" | awk -F'|' '{gsub(/^[ `]+|[ `]+$/, "", $4); print $4}')
      temp_label=$(echo "$line" | awk -F'|' '{gsub(/^[ `]+|[ `]+$/, "", $5); print $5}')
      rating=$(echo "$line" | awk -F'|' '{gsub(/^[ ]+|[ ]+$/, "", $6); print $6}')
      if [[ -n "$rating" ]] && [[ "$rating" =~ ^[1-5]$ ]]; then
        RATED_FILES["${speaker}/${tone}-${temp_label}"]=1
      fi
    elif [[ $in_table -eq 1 ]] && [[ ! "$line" =~ ^\| ]]; then
      in_table=0
    fi
  done < "$EVAL_FILE"
}

# --- Collect ratings in arrays ---
declare -A RATINGS   # key="speaker/tone-tlabel" value="1-5"
declare -A NOTES     # key="speaker/tone-tlabel" value="text"
declare -A DURATIONS # key="speaker/tone-tlabel" value="12.8s"

get_duration() {
  local file="$1"
  if [[ -f "$file" ]]; then
    local dur
    dur=$(ffprobe -v quiet -show_entries format=duration -of csv=p=0 "$file" 2>/dev/null || echo "0")
    LC_NUMERIC=C printf "%.1f" "$dur"
  else
    echo "0.0"
  fi
}

# --- Play audio ---
play_file() {
  local file="$1"
  # ffplay: no display window, auto-exit when done, quiet
  ffplay -nodisp -autoexit -loglevel quiet "$file" 2>/dev/null &
  PLAY_PID=$!
}

stop_playback() {
  if [[ -n "${PLAY_PID:-}" ]] && kill -0 "$PLAY_PID" 2>/dev/null; then
    kill "$PLAY_PID" 2>/dev/null
    wait "$PLAY_PID" 2>/dev/null || true
  fi
  PLAY_PID=""
}

# --- Write evaluation.md ---
write_eval() {
  # Build ordered list of all entries (rated + from this session)
  local count=0
  local entries=()

  for speaker in "${SPEAKERS[@]}"; do
    for tone in "${TONES[@]}"; do
      for i in "${!TEMPERATURES[@]}"; do
        local temp="${TEMPERATURES[$i]}"
        local label="${TEMP_LABELS[$i]}"
        local key="${speaker}/${tone}-${label}"
        count=$((count + 1))

        if [[ -n "${RATINGS[$key]:-}" ]]; then
          local dur="${DURATIONS[$key]:-?}"
          local note="${NOTES[$key]:-}"
          entries+=("| ${count} | \`${speaker}\` | \`${tone}\` | ${temp} | ${RATINGS[$key]} | ${dur}s | ${note} |")
        fi
      done
    done
  done

  local rated_count=${#entries[@]}
  if [[ $rated_count -eq 0 ]]; then
    return
  fi

  # Write file
  cat > "$EVAL_FILE" << 'HEADER'
# Voice Matrix Evaluation

> Generated by `scripts/evaluate-matrix.sh`
> Rating scale: 1=unusable, 2=poor, 3=acceptable, 4=good, 5=production-ready

## Per-file Ratings

| # | Speaker | Tone | Temp | Rating | Duration | Notes |
|---|---------|------|------|--------|----------|-------|
HEADER

  for entry in "${entries[@]}"; do
    echo "$entry" >> "$EVAL_FILE"
  done

  # --- Summary stats ---
  echo "" >> "$EVAL_FILE"
  echo "## Summary" >> "$EVAL_FILE"
  echo "" >> "$EVAL_FILE"
  echo "**Rated**: ${rated_count}/${TOTAL} files" >> "$EVAL_FILE"
  echo "" >> "$EVAL_FILE"

  # Average by speaker
  echo "### Average by Speaker" >> "$EVAL_FILE"
  for speaker in "${SPEAKERS[@]}"; do
    local sum=0 n=0
    for key in "${!RATINGS[@]}"; do
      if [[ "$key" == "${speaker}/"* ]]; then
        sum=$((sum + RATINGS[$key]))
        n=$((n + 1))
      fi
    done
    if [[ $n -gt 0 ]]; then
      local avg
      avg=$(LC_NUMERIC=C awk "BEGIN {printf \"%.2f\", $sum/$n}")
      echo "- \`${speaker}\`: **${avg}** (${n} files)" >> "$EVAL_FILE"
    fi
  done
  echo "" >> "$EVAL_FILE"

  # Average by temperature
  echo "### Average by Temperature" >> "$EVAL_FILE"
  for i in "${!TEMPERATURES[@]}"; do
    local temp="${TEMPERATURES[$i]}"
    local label="${TEMP_LABELS[$i]}"
    local sum=0 n=0
    for key in "${!RATINGS[@]}"; do
      if [[ "$key" == *"-${label}" ]]; then
        sum=$((sum + RATINGS[$key]))
        n=$((n + 1))
      fi
    done
    if [[ $n -gt 0 ]]; then
      local avg
      avg=$(LC_NUMERIC=C awk "BEGIN {printf \"%.2f\", $sum/$n}")
      echo "- temp=${temp}: **${avg}** (${n} files)" >> "$EVAL_FILE"
    fi
  done
  echo "" >> "$EVAL_FILE"

  # Average by tone
  echo "### Average by Tone" >> "$EVAL_FILE"
  for tone in "${TONES[@]}"; do
    local sum=0 n=0
    for key in "${!RATINGS[@]}"; do
      if [[ "$key" == *"/${tone}-"* ]]; then
        sum=$((sum + RATINGS[$key]))
        n=$((n + 1))
      fi
    done
    if [[ $n -gt 0 ]]; then
      local avg
      avg=$(LC_NUMERIC=C awk "BEGIN {printf \"%.2f\", $sum/$n}")
      echo "- \`${tone}\`: **${avg}** (${n} files)" >> "$EVAL_FILE"
    fi
  done
  echo "" >> "$EVAL_FILE"

  # Top 5 and Bottom 5
  # Build sorted list: "rating key" then sort
  local sorted=()
  for key in "${!RATINGS[@]}"; do
    sorted+=("${RATINGS[$key]} ${key}")
  done

  # Sort descending
  IFS=$'\n' sorted_desc=($(printf '%s\n' "${sorted[@]}" | sort -rn)); unset IFS
  # Sort ascending
  IFS=$'\n' sorted_asc=($(printf '%s\n' "${sorted[@]}" | sort -n)); unset IFS

  echo "### Top 5 (Highest Rated)" >> "$EVAL_FILE"
  local show=$((${#sorted_desc[@]} < 5 ? ${#sorted_desc[@]} : 5))
  for ((j=0; j<show; j++)); do
    local r="${sorted_desc[$j]%% *}"
    local k="${sorted_desc[$j]#* }"
    local note="${NOTES[$k]:-}"
    echo "1. **${r}/5** — \`${k}\`${note:+ — ${note}}" >> "$EVAL_FILE"
  done
  echo "" >> "$EVAL_FILE"

  echo "### Bottom 5 (Lowest Rated)" >> "$EVAL_FILE"
  show=$((${#sorted_asc[@]} < 5 ? ${#sorted_asc[@]} : 5))
  for ((j=0; j<show; j++)); do
    local r="${sorted_asc[$j]%% *}"
    local k="${sorted_asc[$j]#* }"
    local note="${NOTES[$k]:-}"
    echo "1. **${r}/5** — \`${k}\`${note:+ — ${note}}" >> "$EVAL_FILE"
  done
}

# --- Load existing ratings into RATINGS/NOTES arrays ---
load_existing_eval() {
  if [[ ! -f "$EVAL_FILE" ]]; then
    return
  fi
  local in_table=0
  while IFS= read -r line; do
    if [[ "$line" =~ ^\|\ *---\| ]]; then
      in_table=1
      continue
    fi
    if [[ $in_table -eq 1 ]] && [[ "$line" =~ ^\| ]]; then
      local speaker tone temp_val rating duration notes
      speaker=$(echo "$line" | awk -F'|' '{gsub(/^[ `]+|[ `]+$/, "", $3); print $3}')
      tone=$(echo "$line" | awk -F'|' '{gsub(/^[ `]+|[ `]+$/, "", $4); print $4}')
      temp_val=$(echo "$line" | awk -F'|' '{gsub(/^[ ]+|[ ]+$/, "", $5); print $5}')
      rating=$(echo "$line" | awk -F'|' '{gsub(/^[ ]+|[ ]+$/, "", $6); print $6}')
      duration=$(echo "$line" | awk -F'|' '{gsub(/^[ ]+|[ ]+$/, "", $7); print $7}')
      notes=$(echo "$line" | awk -F'|' '{gsub(/^[ ]+|[ ]+$/, "", $8); print $8}')

      if [[ -n "$rating" ]] && [[ "$rating" =~ ^[1-5]$ ]]; then
        # Convert temp value to label
        local temp_label=""
        for idx in "${!TEMPERATURES[@]}"; do
          if [[ "${TEMPERATURES[$idx]}" == "$temp_val" ]]; then
            temp_label="${TEMP_LABELS[$idx]}"
            break
          fi
        done
        if [[ -n "$temp_label" ]]; then
          local key="${speaker}/${tone}-${temp_label}"
          RATINGS["$key"]="$rating"
          DURATIONS["$key"]="${duration%s}"  # strip trailing 's'
          NOTES["$key"]="$notes"
        fi
      fi
    elif [[ $in_table -eq 1 ]] && [[ ! "$line" =~ ^\| ]]; then
      in_table=0
    fi
  done < "$EVAL_FILE"
}

# --- Cleanup on exit ---
cleanup() {
  stop_playback
  write_eval
  echo ""
  echo -e "${GREEN}Evaluation saved to:${NC} ${BOLD}${EVAL_FILE}${NC}"
}
trap cleanup EXIT

# --- Main ---
echo ""
echo -e "${BOLD}Voice Matrix Evaluation${NC}"
echo -e "${DIM}Rating scale: 1=unusable  2=poor  3=acceptable  4=good  5=production-ready${NC}"
echo -e "${DIM}Controls: Enter=rate & next  r=replay  s=skip  q=quit & save${NC}"
echo ""

# Load existing ratings for resume
load_existing_eval
EXISTING_COUNT=${#RATINGS[@]}

if [[ $EXISTING_COUNT -gt 0 ]]; then
  echo -e "${YELLOW}Resuming: ${EXISTING_COUNT}/${TOTAL} files already rated, skipping those.${NC}"
  echo ""
fi

# Parse for skip-check
parse_existing_eval

COUNT=0
NEW_RATED=0

for speaker in "${SPEAKERS[@]}"; do
  for tone in "${TONES[@]}"; do
    # Print tone group header
    FIRST_IN_GROUP=1

    for i in "${!TEMPERATURES[@]}"; do
      temp="${TEMPERATURES[$i]}"
      label="${TEMP_LABELS[$i]}"
      key="${speaker}/${tone}-${label}"
      filepath="$MATRIX_DIR/$speaker/${tone}-${label}.wav"
      COUNT=$((COUNT + 1))

      # Skip already rated
      if [[ -n "${RATED_FILES[$key]:-}" ]]; then
        continue
      fi

      # Skip missing files
      if [[ ! -f "$filepath" ]]; then
        echo -e "  ${RED}[${COUNT}/${TOTAL}] MISSING: ${filepath}${NC}"
        continue
      fi

      # Print group header once
      if [[ $FIRST_IN_GROUP -eq 1 ]]; then
        echo -e "${CYAN}── ${speaker} / ${tone} ──${NC}"
        FIRST_IN_GROUP=0
      fi

      # Get duration
      dur=$(get_duration "$filepath")
      DURATIONS["$key"]="$dur"

      # Display file info
      echo -ne "  ${BOLD}[${COUNT}/${TOTAL}]${NC} ${speaker} | ${tone} | temp=${temp} | ${dur}s"
      echo ""

      # Play audio
      play_file "$filepath"

      # Rating loop
      while true; do
        echo -ne "  Rating (1-5): "
        read -r input

        case "$input" in
          r|R)
            stop_playback
            play_file "$filepath"
            echo -e "  ${DIM}Replaying...${NC}"
            continue
            ;;
          s|S)
            stop_playback
            echo -e "  ${DIM}Skipped${NC}"
            break
            ;;
          q|Q)
            stop_playback
            echo ""
            echo -e "${YELLOW}Quitting. ${NEW_RATED} new ratings this session.${NC}"
            exit 0
            ;;
          [1-5])
            stop_playback
            RATINGS["$key"]="$input"

            # Ask for notes
            echo -ne "  Notes (optional): "
            read -r note_input
            NOTES["$key"]="$note_input"

            NEW_RATED=$((NEW_RATED + 1))
            local_total=$((EXISTING_COUNT + NEW_RATED))
            echo -e "  ${GREEN}Saved${NC} (${local_total}/${TOTAL} total)"
            echo ""
            break
            ;;
          *)
            echo -e "  ${RED}Invalid. Enter 1-5, r=replay, s=skip, q=quit${NC}"
            ;;
        esac
      done
    done
  done
done

# --- Completion ---
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
TOTAL_RATED=${#RATINGS[@]}
echo -e "${GREEN}Done!${NC} ${TOTAL_RATED}/${TOTAL} files rated (${NEW_RATED} new this session)"
